"""renamed_month_month_norm_cols

Revision ID: 2f7553b4a103
Revises: bd73d5c3550d
Create Date: 2025-11-14 19:45:08.939992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f7553b4a103'
down_revision: Union[str, Sequence[str], None] = 'bd73d5c3550d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_data', sa.Column('norm_1mo', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.add_column('stock_data', sa.Column('norm_3mo', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.add_column('stock_data', sa.Column('norm_6mo', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.drop_column('stock_data', 'norm_3m')
    op.drop_column('stock_data', 'norm_1m')
    op.drop_column('stock_data', 'norm_6m')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_data', sa.Column('norm_6m', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('stock_data', sa.Column('norm_1m', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('stock_data', sa.Column('norm_3m', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_column('stock_data', 'norm_6mo')
    op.drop_column('stock_data', 'norm_3mo')
    op.drop_column('stock_data', 'norm_1mo')
    # ### end Alembic commands ###
