"""updated_decimal_stock_price

Revision ID: 50f99623dd55
Revises: acd519ad7b8a
Create Date: 2025-11-06 00:12:45.330815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f99623dd55'
down_revision: Union[str, Sequence[str], None] = 'acd519ad7b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_data', 'open',
               existing_type=sa.NUMERIC(precision=12, scale=5),
               type_=sa.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('stock_data', 'high',
               existing_type=sa.NUMERIC(precision=12, scale=5),
               type_=sa.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('stock_data', 'low',
               existing_type=sa.NUMERIC(precision=12, scale=5),
               type_=sa.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('stock_data', 'close',
               existing_type=sa.NUMERIC(precision=12, scale=5),
               type_=sa.DECIMAL(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_data', 'close',
               existing_type=sa.DECIMAL(precision=12, scale=2),
               type_=sa.NUMERIC(precision=12, scale=5),
               existing_nullable=False)
    op.alter_column('stock_data', 'low',
               existing_type=sa.DECIMAL(precision=12, scale=2),
               type_=sa.NUMERIC(precision=12, scale=5),
               existing_nullable=False)
    op.alter_column('stock_data', 'high',
               existing_type=sa.DECIMAL(precision=12, scale=2),
               type_=sa.NUMERIC(precision=12, scale=5),
               existing_nullable=False)
    op.alter_column('stock_data', 'open',
               existing_type=sa.DECIMAL(precision=12, scale=2),
               type_=sa.NUMERIC(precision=12, scale=5),
               existing_nullable=False)
    # ### end Alembic commands ###
