"""drop norm_20y table

Revision ID: 9eef5ef4a972
Revises: 2f7553b4a103
Create Date: 2026-02-02 18:00:48.372789

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9eef5ef4a972"
down_revision: Union[str, Sequence[str], None] = "2f7553b4a103"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_data", "norm_20y")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stock_data",
        sa.Column(
            "norm_20y",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
