"""stock_data_init

Revision ID: acd519ad7b8a
Revises: 
Create Date: 2025-11-05 22:47:59.067672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd519ad7b8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=12, scale=5), nullable=False),
    sa.Column('high', sa.DECIMAL(precision=12, scale=5), nullable=False),
    sa.Column('low', sa.DECIMAL(precision=12, scale=5), nullable=False),
    sa.Column('close', sa.DECIMAL(precision=12, scale=5), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_symbol_date')
    )
    op.create_index('idx_symbol_date', 'stock_data', ['symbol', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_symbol_date', table_name='stock_data')
    op.drop_table('stock_data')
    # ### end Alembic commands ###
