"""add_normalized_price_time_horizons

Revision ID: bd73d5c3550d
Revises: d18f3ab4e8ac
Create Date: 2025-11-07 23:23:12.577767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd73d5c3550d"
down_revision: Union[str, Sequence[str], None] = "d18f3ab4e8ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stock_data",
        sa.Column("norm_1m", sa.DECIMAL(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "stock_data",
        sa.Column("norm_3m", sa.DECIMAL(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "stock_data",
        sa.Column("norm_6m", sa.DECIMAL(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "stock_data",
        sa.Column("norm_1y", sa.DECIMAL(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "stock_data",
        sa.Column("norm_5y", sa.DECIMAL(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "stock_data",
        sa.Column("norm_20y", sa.DECIMAL(precision=12, scale=2), nullable=True),
    )
    op.drop_column("stock_data", "normalized_price")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stock_data",
        sa.Column(
            "normalized_price",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("stock_data", "norm_20y")
    op.drop_column("stock_data", "norm_5y")
    op.drop_column("stock_data", "norm_1y")
    op.drop_column("stock_data", "norm_6m")
    op.drop_column("stock_data", "norm_3m")
    op.drop_column("stock_data", "norm_1m")
    # ### end Alembic commands ###
