"""add_normalized_price_row

Revision ID: d18f3ab4e8ac
Revises: 50f99623dd55
Create Date: 2025-11-06 12:49:37.822963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18f3ab4e8ac'
down_revision: Union[str, Sequence[str], None] = '50f99623dd55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_data', sa.Column('normalized_price', sa.DECIMAL(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_data', 'normalized_price')
    # ### end Alembic commands ###
